name: publicación de mi pagina web

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist # Asegúrate de que este sea el directorio de salida de tu proyecto
        publish_branch: gh-pages # Opcional: asegura que el despliegue ocurra en esta rama
        force_orphan: true # Opcional: limpia la rama gh-pages si hay historial previo
